// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGXna4J8vYObVJCz8F-YGNkQi_xqcO7ZE',
    appId: '1:380935557028:web:fc140ebb6edb34a04cbb31',
    messagingSenderId: '380935557028',
    projectId: 'easyshopping-d21de',
    authDomain: 'easyshopping-d21de.firebaseapp.com',
    storageBucket: 'easyshopping-d21de.appspot.com',
    measurementId: 'G-L6KQ2JDSEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCslSseB9HGrcWP0Cb0ujUVXBaEViWuzwM',
    appId: '1:380935557028:android:7e58c01bdc67b34a4cbb31',
    messagingSenderId: '380935557028',
    projectId: 'easyshopping-d21de',
    storageBucket: 'easyshopping-d21de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4_BYVwGrbYMsjsHXpbcazLDKHYm8wZ3Q',
    appId: '1:380935557028:ios:bc5853eb9692cdba4cbb31',
    messagingSenderId: '380935557028',
    projectId: 'easyshopping-d21de',
    storageBucket: 'easyshopping-d21de.appspot.com',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4_BYVwGrbYMsjsHXpbcazLDKHYm8wZ3Q',
    appId: '1:380935557028:ios:bc5853eb9692cdba4cbb31',
    messagingSenderId: '380935557028',
    projectId: 'easyshopping-d21de',
    storageBucket: 'easyshopping-d21de.appspot.com',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGXna4J8vYObVJCz8F-YGNkQi_xqcO7ZE',
    appId: '1:380935557028:web:300c3c410947e62c4cbb31',
    messagingSenderId: '380935557028',
    projectId: 'easyshopping-d21de',
    authDomain: 'easyshopping-d21de.firebaseapp.com',
    storageBucket: 'easyshopping-d21de.appspot.com',
    measurementId: 'G-9M0HNQHTEN',
  );
}
